coverage:
  status:
    project:
      default:
        # set target to fail the build if coverage is too low
        target: 50%
    patch:
      default:
        # basic just to show current patch
        target: 0%
        threshold: 0%
        base: auto

# temporarily avoid comments to PRs and so on
comment: false
