# Supervised Classification Preset
backbone: transformer
head: classification
backbone_config:
  hidden_dim: 256
  num_layers: 4
  num_heads: 8
  dropout: 0.1
head_config:
  num_classes: 10
  pool_type: mean
training:
  max_epochs: 20
  learning_rate: 0.0003
  mixed_precision: "fp16"
data:
  batch_size: 64
  num_samples: 5000
  seq_len: 100
